# Generated by Django 2.0.2 on 2018-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181115_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Proyect',
        ),
    ]
