# Generated by Django 2.0.2 on 2018-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181115_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
    ]
